spring:
  profiles:
    active: test
---
spring:
  profiles: development
  redis:
    host: localhost
    port: 6379
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://136.243.174.198:13306/dev?useSSL=false
    username: root
    password: dbpass
---
spring:
  profiles: test
  redis:
    host: localhost
    port: 6379
  jpa:
    database: H2